---
- name: Scan host for facts
  hosts: all
  become: true

  tasks:
    - name: Get packages
      ansible.builtin.package_facts:
      register: package_facts

    - name: Print raw package result
      ansible.builtin.debug:
        var: package_facts
        verbosity: 2

    - name: Get services
      ansible.builtin.service_facts:
      register: service_facts

    - name: Print raw service result
      ansible.builtin.debug:
        var: service_facts
        verbosity: 2
