---
- name: Ensure required packages are installed on all hosts
  hosts: all
  gather_facts: false
  become: true
  vars:
    become_user: ec2-user

  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - cifs-utils
          - p11-kit
          - ca-certificates
          - java-11-openjdk
        state: present
