---
- name: Retrieve and install cert on cert-builder
  hosts: cert-builder
  become: true
  become_user: ec2-user
  vars:
    cert_share: "//node3/samba_share"
    mount_point: /mnt/palo_certs
   # cifs_user: your_user
   # cifs_pass: your_password

  tasks:
    - name: Ensure mount point exists
      ansible.builtin.file:
        path: "{{ mount_point }}"
        state: directory

    - name: Mount CIFS share
      ansible.posix.mount:
        path: "{{ mount_point }}"
        src: "{{ cert_share }}"
        fstype: cifs
      #  opts: "username={{ cifs_user }},password={{ cifs_pass }},ro"
        state: mounted

    - name: Find the only .crt file
      ansible.builtin.shell: ls {{ mount_point }}/*.crt
      register: cert_name
      changed_when: false

    - name: Set dynamic cert_file name
      ansible.builtin.set_fact:
        cert_file: "{{ cert_name.stdout | basename }}"

    - name: Copy cert to anchors
      ansible.builtin.copy:
        src: "{{ mount_point }}/{{ cert_file }}"
        dest: "/etc/pki/ca-trust/source/anchors/{{ cert_file }}"
        remote_src: true

    - name: Unmount share
      ansible.posix.mount:
        path: "{{ mount_point }}"
        state: unmounted

    - name: Update CA trust
      ansible.builtin.command: update-ca-trust

    - name: Generate Java cacerts
      ansible.builtin.command: >
        p11-kit extract --format=java-cacerts --filter=certificates --overwrite --purpose server-auth
        /etc/pki/ca-trust/extracted/java/cacerts

    - name: Save cert name for downstream playbook
      ansible.builtin.copy:
        content: "{{ cert_file }}"
        dest: /tmp/current_cert_name.txt
