---
- name: Distribute cert and Java cacerts to all other hosts
  hosts: all
  gather_facts: false
  become: true
  vars:
    source_host: node1
    ansible_user: ec2-user
    
  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - ca-certificates
        # This below package is required if and when using keytool command on remote hosts. 
        # - java-11-openjdk
        state: present
        
    - name: Get cert filename from cert builder
      ansible.builtin.slurp:
        src: /tmp/current_cert_name.txt
      delegate_to: "{{ source_host }}"
      run_once: true
      register: cert_name_data

    - name: Set cert_file fact
      ansible.builtin.set_fact:
        cert_file: "{{ cert_name_data['content'] | b64decode | trim }}"

    - name: Fetch .crt from cert builder
      ansible.builtin.fetch:
        src: "/etc/pki/ca-trust/source/anchors/{{ cert_file }}"
        dest: "/tmp/{{ cert_file }}"
        flat: yes
      delegate_to: "{{ source_host }}"
      run_once: true

    - name: Push .crt to this host
      ansible.builtin.copy:
        src: "/tmp/{{ cert_file }}"
        dest: "/etc/pki/ca-trust/source/anchors/{{ cert_file }}"
        remote_src: false
        owner: root
        group: root
        mode: '0644'

    - name: Validate that cert file was copied and is not empty
      ansible.builtin.stat:
        path: "/etc/pki/ca-trust/source/anchors/{{ cert_file }}"
      register: cert_stat

    - name: Fail if the cert file is empty or missing
      ansible.builtin.fail:
        msg: "The certificate file {{ cert_file }} is missing or empty on {{ inventory_hostname }}."
      when: cert_stat.stat.size == 0

    - name: Fetch Java cacerts from cert builder
      ansible.builtin.fetch:
        src: "/etc/pki/ca-trust/extracted/java/cacerts"
        dest: "/tmp/cacerts"
        flat: yes
      delegate_to: "{{ source_host }}"
      run_once: true

    - name: Push Java cacerts to this host
      ansible.builtin.copy:
        src: "/tmp/cacerts"
        dest: "/etc/pki/ca-trust/extracted/java/cacerts"
        remote_src: false
        owner: root
        group: root
        mode: '0644'

    - name: Update CA trust
      ansible.builtin.command: update-ca-trust
