---
- name: Distribute cert and Java cacerts to all other hosts
  hosts: all
  gather_facts: false
  become: true
  vars:
    source_host: node1
    ansible_user: ec2-user
    
  tasks:
    - name: Get cert filename from cert builder
      ansible.builtin.slurp:
        src: /tmp/current_cert_name.txt
      delegate_to: "{{ source_host }}"
      run_once: true
      register: cert_name_data

    - name: Set cert_file fact
      ansible.builtin.set_fact:
        cert_file: "{{ cert_name_data['content'] | b64decode | trim }}"

    - name: Fetch .crt from cert builder
      ansible.builtin.fetch:
        src: "/etc/pki/ca-trust/source/anchors/{{ cert_file }}"
        dest: "/tmp/{{ cert_file }}"
        flat: yes
      delegate_to: "{{ source_host }}"
      run_once: true

    - name: Push .crt to this host
      ansible.builtin.copy:
        src: "/tmp/{{ cert_file }}"
        dest: "/etc/pki/ca-trust/source/anchors/{{ cert_file }}"
        remote_src: false
        owner: root
        group: root
        mode: '0644'

    - name: Fetch Java cacerts from cert builder
      ansible.builtin.fetch:
        src: "/etc/pki/ca-trust/extracted/java/cacerts"
        dest: "/tmp/cacerts"
        flat: yes
      delegate_to: "{{ source_host }}"
      run_once: true

    - name: Push Java cacerts to this host
      ansible.builtin.copy:
        src: "/tmp/cacerts"
        dest: "/etc/pki/ca-trust/extracted/java/cacerts"
        remote_src: false
        owner: root
        group: root
        mode: '0644'

    - name: Update CA trust
      ansible.builtin.command: update-ca-trust

    - name: Validate dummy cert is present in Java cacerts
      ansible.builtin.shell: >
        keytool -list -keystore /etc/pki/ca-trust/extracted/java/cacerts -storepass changeit | grep -i dummy
      register: cert_validation
      changed_when: false
      failed_when: cert_validation.rc != 0

    - name: Show validation result
      debug:
        msg: "Dummy cert found in Java cacerts: {{ cert_validation.stdout }}"

