---
- name: Distribute detected cert to prod servers
  hosts: all:!cert-builder
  become: true
  vars:
    source_host: node1

  tasks:

    - name: Read cert name from cert-builder
      ansible.builtin.slurp:
        src: /tmp/current_cert_name.txt
      delegate_to: "{{ source_host }}"
      run_once: true
      register: cert_name_data

    - name: Set cert_file fact
      ansible.builtin.set_fact:
        cert_file: "{{ cert_name_data['content'] | b64decode | trim }}"

    - name: Fetch .crt from cert-builder
      ansible.builtin.fetch:
        src: "/etc/pki/ca-trust/source/anchors/{{ cert_file }}"
        dest: "/tmp/{{ cert_file }}"
        flat: yes
      delegate_to: "{{ source_host }}"
      run_once: true

    - name: Push .crt to this host
      ansible.builtin.copy:
        src: "/tmp/{{ cert_file }}"
        dest: "/etc/pki/ca-trust/source/anchors/{{ cert_file }}"
        remote_src: false

    - name: Fetch Java cacerts from cert-builder
      ansible.builtin.fetch:
        src: "/etc/pki/ca-trust/extracted/java/cacerts"
        dest: "/tmp/cacerts"
        flat: yes
      delegate_to: "{{ source_host }}"
      run_once: true

    - name: Push Java cacerts to this host
      ansible.builtin.copy:
        src: "/tmp/cacerts"
        dest: "/etc/pki/ca-trust/extracted/java/cacerts"
        remote_src: false

    - name: Update Linux CA trust
      ansible.builtin.command: update-ca-tr
