---
- name: Cert copy on Linux Servers
  hosts: all
  become: true
  become_user: root
  tasks:

    - name: Backup cacerts file using shell command
      ansible.builtin.shell: cp /etc/pki/ca-trust/extracted/java/cacerts /etc/pki/ca-trust/extracted/java/cacerts.back

    - name: List directories
      ansible.builtin.shell: "cd /opt/certs/ && ls -lrt"
      become: false  # No need for elevated permissions just to list

    - name: Find certificate files on remote host
      ansible.builtin.find:
        paths: /opt/certs/
        patterns: "*.crt"
      register: found_certs

    - name: Copy certificate files to anchors
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: /etc/pki/ca-trust/source/anchors/
        remote_src: yes
      loop: "{{ found_certs.files }}"

    - name: Update CA trust
      ansible.builtin.command: update-ca-trust

    - name: Regenerate Java cacerts file
      ansible.builtin.command: >
        p11-kit extract --format=java-cacerts --filter=certificates
        --overwrite --purpose server-auth /etc/pki/ca-trust/extracted/java/cacerts
