---
- name: Cert copy on Linux Servers
  hosts: all
  become: true
  become_user: root
  tasks:

    - name: Backup cacerts file to root directory
      ansible.builtin.shell: cp /etc/pki/ca-trust/extracted/java/cacerts /root/cacerts.back
      become: true

    - name: Ensure /opt/certs/ exists
      ansible.builtin.stat:
        path: /opt/certs/
      register: certs_dir

    - name: List directories
      ansible.builtin.shell: "cd /opt/certs/ && ls -lrt"
      when: certs_dir.stat.exists
      
    - name: Find certificate files on remote host
      ansible.builtin.find:
        paths: /opt/certs/
        patterns: "*.crt"
      register: found_certs
  
    - name: Copy certificate files to anchors
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: /etc/pki/ca-trust/source/anchors/
        remote_src: yes
      loop: "{{ found_certs.files }}"
  
 #  - name: Set SELinux to permissive (temporary)
 #    ansible.builtin.command: setenforce 0
 #    become: true
      
#   - name: Update CA trust
#     ansible.builtin.command: update-ca-trust
#     register: update_ca_result
#     become: true

#    - name: Show output if update-ca-trust failed
#      ansible.builtin.debug:
#        var: update_ca_result.stderr
#     when: update_ca_result.rc != 0
      
    - name: Regenerate Java cacerts file
      ansible.builtin.command: >
        p11-kit extract --format=java-cacerts --filter=certificates
        --overwrite --purpose server-auth /etc/pki/ca-trust/extracted/java/cacerts
