---
- name: Cert copy on Linux Servers
  hosts: all
  become: true
  become_user: root
  tasks:

    - name: Backup cacerts file to /root
      ansible.builtin.shell: cp /etc/pki/ca-trust/extracted/java/cacerts /root/cacerts.back
      ignore_errors: true

    - name: Ensure /opt/certs/ directory exists
      ansible.builtin.stat:
        path: /opt/certs/
      register: certs_dir

    - name: List certs in /opt/certs if present
      ansible.builtin.shell: ls -lrt /opt/certs/
      when: certs_dir.stat.exists

    - name: Find certificate files on remote host
      ansible.builtin.find:
        paths: /opt/certs/
        patterns: "*.crt"
      register: found_certs
      when: certs_dir.stat.exists

    - name: Copy certificate files to anchors
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: /etc/pki/ca-trust/source/anchors/
        remote_src: yes
      loop: "{{ found_certs.files }}"
      when: certs_dir.stat.exists and found_certs.matched > 0

    - name: Extract Java cacerts to /root/cacerts
      ansible.builtin.command: >
        p11-kit extract --format=java-cacerts --filter=certificates
        --overwrite --purpose server-auth /root/cacerts
