---
- name: Manage Java Keystore and System CA Trust for All Certs
  hosts: all
  become: true
  vars:
    cert_search_path: /etc/pki/ca-trust/source/anchors/
    cert_pattern: "*.crt"
    java_keystore_path: /opt/demo-keystore/cacerts
    java_keystore_password: changeit

  tasks:
    - name: Gather current user info
      ansible.builtin.setup:
        filter: ansible_user

    - name: Find all certs to process
      ansible.builtin.find:
        paths: "{{ cert_search_path }}"
        patterns: "{{ cert_pattern }}"
        file_type: file
      register: certs_found

    - name: Fail if no certs found
      ansible.builtin.fail:
        msg: "No cert files matching {{ cert_pattern }} found in {{ cert_search_path }}"
      when: certs_found.matched == 0

    - name: Loop over each cert
      block:
        - name: Copy cert to EE-accessible path
          ansible.builtin.copy:
            src: "{{ item.path }}"
            dest: "/tmp/{{ item.path | basename }}"
            remote_src: yes

        - name: Import cert into Java keystore
          community.general.java_cert:
            cert_path: "/tmp/{{ item.path | basename }}"
            keystore_path: "{{ java_keystore_path }}"
            keystore_pass: "{{ java_keystore_password }}"
            keystore_create: true
            state: present
            cert_alias: "{{ item.path | basename | regex_replace('\\.[^.]+$', '') }}"
            trust_cacert: true

        - name: Copy cert to system trust anchors
          ansible.builtin.copy:
            src: "{{ item.path }}"
            dest: "/etc/pki/ca-trust/source/anchors/{{ item.path | basename }}"
            remote_src: yes

      loop: "{{ certs_found.files }}"

    - name: Update system CA trust
      ansible.builtin.command: update-ca-trust
